### ISSUE TITLE
My comment

### ISSUE THREAD

**Issue by KamenskiyKonstantin** [Dimon20012008/InformaticsProjectCV9#1]
Проблемы
(1-3 - проблемы mediapipe)
1. Проект иногда теряет палец и не реагирует на движения
2. Проект иногда видит два пальца и переключается между ними, создавая лишние линии
3. Проект иногда распознает как конец указательного пальца другие части кисти и рисует по ним
4. Оценка результатов не всегда соответствует действительности - прямая набрал 50% сходства с кругом а закрашенный круг(не контур) - 70%
Сильные стороны - оригинальная задумка, неплохая реализация
Пожелания: добавить запрет на рисование в обратную сторону, разные контуры и цвета, изменить систему подсчета процентов

**Comment by Dimon20012008** [comment]
1-3. Ну, бывает, это проблемы mediapipe. Добавил инструкции в README
4. А вот это правда, теперь при кривых контурах результат ниже и определяются они лучше
