### ISSUE TITLE
Комментарий от Ивана Фенстера

### ISSUE THREAD

**Issue by IvanFenster** [Dimon20012008/InformaticsProjectCV9#2]
Проблемы:
- Если палец изначально вне экрана, то линия все равно рисуеться, но не понятно, куда доводить линию для завершения программы.
- При появлении второй, даже случайной, руки точка может перекинуться на неё, что полностью ломает выводимую фигуру.

Совет: 
- Просто напиши в README, что не следует допускать посторонних рук в кадре и ответственность ляжет на пользователя.
- Сделай так, чтобы он требовал, чтобы палец изначально был в окне.

**Comment by Dimon20012008** [comment]
Добавил комментарии в README, спасибо огромное за предложение
