### ISSUE TITLE
Точность измерений

### ISSUE THREAD

**Issue by martynovalexandr** [Dimon20012008/InformaticsProjectCV9#3]
Здравствуй, Дим! Протестировал твой проект. И могу сказать, что мне очень понравилось, идея очень классная и если не крутить пальцем по всему экрану и не видеть эту проблему, то играть очень даже интересно и прикольно.
Но все же вернемся к проблеме:
Точность измерения при почти любой фигуре достаточно большая, я имею ввиду, что я могу нарисовать фигуру, совсем не похожую на круг, но при этом достигнуть достаточно большой точности (60-70%)
Мои идеи по улучшению:
Я бы подмуал над ограничением пространства по которому в целом может двигаться наш палец, и тогда, кажется, проблема именно с большим выходом за рамки уйдет. Я имею ввиду, нарисуем условную окружность с тем же центром, что и на экране, но с бОльшим радиусом, и вот, если палец выходит за края этой окружности, то сбрасывать попытку.

С уважение,
тестировщик в лице Мартынова Саши

**Comment by Dimon20012008** [comment]
Спасибо за замечание. Решил легче - вместо среднего расстояний взял среднее экспонент расстояний: теперь большие расстояния значительно влияют на среднее
